name: Test 
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cargo build
        run: cargo build --verbose
      - name: Cargo test 
        run: cargo test --verbose
